### PR TITLE
Fix Polars 0.13.58 build and newer.

### PR DESCRIPTION
**Pull request by ghuls**
Fix Polars 0.13.58 build and newer:
  - Update rust from 1.61.0 to 1.63.0.
  - Update maturin to =0.13,<0.14 which does not
    build source distributions by default anymore.

### CODE REVIEW

**Comment by ritchie46** [comment]
Somehow it doesn't take rust nightly. 

```
   Compiling arrow2 v0.12.0 (https://github.com/jorgecarleitao/arrow2?rev=c720eb26d426f7c3e1d1ea9e5650efcb83019732#c720eb26)
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> $BUILD_PREFIX/.cargo/git/checkouts/arrow2-8a2ad61d97265680/c720eb2/src/lib.rs:12:39
   |
12 | #![cfg_attr(feature = "simd", feature(portable_simd))]
   |                                       ^^^^^^^^^^^^^


error: aborting due to previous error


```

**Comment by ritchie46** [comment]
@Maxyme Do you know how we can set the nightly compiler?

**Comment by ghuls** [comment]
With the first commit, it was building ok (or at least 50 minutes) except for MacOS (due to an outdated image), before I pushed the second patch which installs `rust_linux-64` (1.61.0 available) instead of `rust[subdir=linux-64]` (1.63.0 available). Not sure why there are so many different rust packages and why they are not linked.

**Comment by ritchie46** [comment]
Thanks a lot @ghuls. That fixes all builds, save from macos arm. I will merge this as that is a lot better than the current state.

**Comment by timkpaine** [comment]
Did you bump the build number as specified in the PR instructions?

**Comment by ritchie46** [comment]
> Did you bump the build number as specified in the PR instructions? When you open a PR there are a sequence of instructions that you should take care to follow.

Nope, I shall follow up with a PR on that.

**Comment by timkpaine** [comment]
No need, as there are later versions that should work now it will only be a temporary problem until a new version is merged

**Pull request merged**
