### PR TITLE
Use mold as linker

### PR DESCRIPTION
**Pull request by 0xbe7a**
Use mold as linker. Requires #161 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timkpaine** [comment]
What's the value-add to this?

**Comment by 0xbe7a** [comment]
> What's the value-add to this? I don't see polars using `mold` itself for its CI or python wheel builds, this should probably be upstreamed first.

The value add is reduced CI resource usage, currently each built takes >24h of built time in total. A large fraction is of this time is spent with linking. 

I don’t think upstream should require a specific linker, as it’s a just a generic part of the compiler toolchain. 
coda-forge also already uses different linker backends (gcc linker on linux / clang on Mac OS) already.

Getting mold to work with aarch64 / conda-forge seems a bit finicky right now and im not quite sure why jemallac currently fails. It also seems like no other feedstock currently uses mold for linking.

**Comment by 0xbe7a** [comment]
Ok I just checked the impact and it shaves of about 3 minutes of build time per build. This is probably due to the runners just having 2 cores. IMHO 3 minutes is probably not worth the hassle, so I will close this.

**Comment by timkpaine** [comment]
the build for this has already been super finicky which is why I ask, one extra build dependency is one extra thing that can go wrong 😅

**Comment by xhochy** [comment]
Time savings aren't so relevant but memory usage would be interesting.

**Comment by timkpaine** [comment]
definitely, at a high level "moves towards less finicky" is the goal. Memory usage has caused lots of issues, so a slightly-weirder-but-more-stable build would be valuable.

**Pull request closed without merging**
