### PR TITLE
polars v0.14.2

### PR DESCRIPTION
**Pull request by ritchie46**

### CODE REVIEW

**Comment by ritchie46** [comment]
I still don't really understand how I can ensure we use a specific rust nightly version. Do you know @timkpaine?

**Comment by timkpaine** [comment]
@ritchie46 it is already using the nightly version, but "nightly version" is manually propagated to conda forge. So if there are new features in a newer rust nightly than we have, the version of rust nightly needs to be updated on the rust feedstock like this https://github.com/conda-forge/rust-feedstock/pull/87

**Comment by timkpaine** [comment]
conversation with @xhochy here https://github.com/conda-forge/staged-recipes/pull/18906#issuecomment-1126994556

**Comment by timkpaine** [comment]
My desire to publish rust-nightly as its own package so it automatically ticks up versions: https://github.com/conda-forge/staged-recipes/pull/18906#issuecomment-1127929814

**Comment by timkpaine** [comment]
@jakirkham and @isuruf disagreed and said "just ask rust to bump the version" here: https://github.com/conda-forge/staged-recipes/pull/18906#issuecomment-1128207577

**Comment by timkpaine** [comment]
(clearly the "just ask the rust maintainers to bump the nightly version" is not the most sustainable or scalable decision, but I am not a conda forge admin)

**Comment by timkpaine** [comment]
last rust nightly is 20220529 https://github.com/conda-forge/rust-feedstock/tree/dev/recipe

**Comment by ritchie46** [comment]
Right.. Am I correct that we can only the nightly version set in that feedstock? I can imagine that there will be repo's that need a specific compiler other than the one provide.

For instance, latest polars only compiles with `rustc 1.65.0-nightly`, because the nightly SIMD API has changed recently. Or can feedstocks be versioned, and any version in the history is valid.

**Comment by timkpaine** [comment]
> Right.. Am I correct that we can only the nightly version set in that feedstock? I can imagine that there will be repo's that need a specific compiler other than the one provide.
> 
> For instance, latest polars only compiles with `rustc 1.65.0-nightly`, because the nightly SIMD API has changed recently. Or can feedstocks be versioned, and any version in the history is valid.

you can use any published version through time, so long as the version has been published. let me get the list

**Comment by timkpaine** [comment]
but again, because @isuruf and @jakirkham want this to be a manual process, only manually added versions of rust nightly will be present, rather than for a normal feedstock where new versions are continuously propagated by bot

**Comment by ritchie46** [comment]
> but again, because @isuruf and @jakirkham want this to be a manual process, only manually added versions of rust nightly will be present, rather than for a normal feedstock where new versions are continuously propagated by bot

I understand. Thanks!

**Comment by timkpaine** [comment]
I will also note:
https://github.com/conda-forge/staged-recipes/pull/18906#issuecomment-1126994710
and
https://github.com/conda-forge/staged-recipes/pull/18906#issuecomment-1127929814

> Would it be crazy to publish rust-nightly directly on conda forge? Unlike other pre-release version, it seems many libraries treat rust-nightly as a production equivalent. And I expect many more python packages will have rust nightly dependencies, repeating this exercise isn't going to scale well.

Any thoughts @isuruf / @jakirkham / @xhochy ?

**Comment by isuruf** [comment]
> Polars is extremely fast moving, without automated rebuilding of rust-dev on every nightly release, I don't think it will be sustainable

That's easy to fix. Add code to the bot to send PRs to update once every week.

> Would it be crazy to publish rust-nightly directly on conda forge? Unlike other pre-release version, it seems many libraries treat rust-nightly as a production equivalent. And I expect many more python packages will have rust nightly dependencies, repeating this exercise isn't going to scale well.

What does that achieve? It's a build time only requirement and end users don't have to worry about that.

**Comment by timkpaine** [comment]
> That's easy to fix. Add code to the bot to send PRs to update once every week.
Sounds like a plan, can you point to some docs on this?

> What does that achieve? It's a build time only requirement and end users don't have to worry about that.
Package maintainers get a relatively convoluted set of steps in order to enable something that rust makes very easy via native tools, rather than saying "use rust-nightly instead of rust". The latter is much closer to e.g. `rustup` behavior.

**Comment by isuruf** [comment]
Here's an example https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_sources.py#L207

> Package maintainers get a relatively convoluted set of steps in order to enable something that rust makes very easy via native tools, rather than saying "use rust-nightly instead of rust". 

What's so convoluted about adding just
```
channel_sources:
- conda-forge/label/rust_dev,conda-forge
```

**Comment by timkpaine** [comment]
> What's so convoluted about adding just
> 
> ```
> channel_sources:
> - conda-forge/label/rust_dev,conda-forge
> ```

I mean for one, the fact that its called "dev" and not "nightly", and then also the fact that it is not at all "nightly" and just some random version picked by the last person who had a problem when they expected "nightly" to mean "nightly" 😆

**Comment by ritchie46** [comment]
> I mean for one, the fact that its called "dev" and not "nightly", and then also the fact that it is not at all "nightly" and just some random version picked by the last person who had a problem when they expected "nightly" to mean "nightly"

This was definitely my confusion. Especially nightly can come with bugs, so you might need to pin a very specific version. In rustup we can set the release date, e.g. `nightly-2022-08-16`. 

There can be collisions with a version.

For instance `nightly-2022-08-16` might compile where `nightly-2022-08-15` would not. Both would be versioned `1.65.0`.

**Comment by isuruf** [comment]
> I mean for one, the fact that its called "dev" and not "nightly", and then also the fact that it is not at all "nightly" and just some random version picked by the last person who had a problem when they expected "nightly" to mean "nightly" laughing

LOL. That's exactly why it's called dev and not nightly.

> For instance nightly-2022-08-16 might compile where nightly-2022-08-15 would not. Both would be versioned 1.65.0.

You can just add `rust 1.65.0.2022.08.16` in your `recipe/meta.yaml` to use that specific version

**Comment by timkpaine** [comment]
> LOL. That's exactly why it's called dev and not nightly.
but "rust dev" is not a thing for rust developers, whereas "rust nightly" is. Also when approached by people confused by something, dismissing their confusion is generally not the best way to solve the problem. I think if we setup the bot to update on some regular interval (doesnt have to be daily) and add examples and clarification about "nightly" vs "dev" to the conda docs, then this can be much more understandable.

**Comment by isuruf** [comment]
> To be productive, I think if we setup the bot to update on some regular interval (doesnt have to be daily) and add examples and clarification about "nightly" vs "dev" to the conda docs, then this can be much more understandable.

Sure. We are already swamped as is. PRs are welcome.

**Comment by isuruf** [comment]
> but "rust dev" is not a thing for rust developers, whereas "rust nightly" is. Also when approached by people confused by something, dismissing their confusion is generally not the best way to solve the problem.

Well, you suggested nightly as a better name and then was not happy that the new name was not good whereas the old name fixes your concern.

**Comment by isuruf** [comment]
> but "rust dev" is not a thing for rust developers

`dev` is a standard for conda-forge and going out of the standard is not good. (Your suggestion is to not go out of the standard for rust). So it's a matter of which standard to use when there are two conflicting standards.

**Comment by timkpaine** [comment]
> `dev` is a standard for conda-forge and going out of the standard is not good. (Your suggestion is to not go out of the standard for rust). So it's a matter of which standard to use when there are two conflicting standards.

I'm happy to keep `dev`, we should just tweak the compilers section of the docs. this plus a non-nightly run rate (too much for the bot) and it should be fine. 

> Sure. We are already swamped as is. PRs are welcome.

happy to help, just wanted to make sure ahead of time that its ok and needed some help on bot control

**Comment by jakirkham** [comment]
If we add other label naming, [the CFEP]( https://github.com/conda-forge/cfep/blob/main/cfep-05.md#specification ) would also need to be updated

**Comment by timkpaine** [comment]
closing, to do in https://github.com/conda-forge/polars-feedstock/pull/40

**Pull request closed without merging**
