### PR TITLE
Enable Windows builds.

### PR DESCRIPTION
**Pull request by Maxyme**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timkpaine** [comment]
@conda-forge-admin please rerender

**Comment by dhirschfeld** [comment]
```
error: failed to run the Python interpreter at D:\bld\polars_1654700150952\_build_env\python.exe:
The system cannot find the file specified.
```

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge/polars Any further thoughts or can we merge?

**Comment by Maxyme** [comment]
@xhochy Thanks for the help, looks good to me!

**Pull request merged**
