### PR TITLE
Compile linux_aarch64

### PR DESCRIPTION
**Pull request by tanaka-de-silva**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanakadesilva** [comment]
Tried quite a few permutations to no avail. The CPython packages builds fine locally when you build it natively (using Docker on Apple Silicon), and when cross-compiling for `aarch64` on a Linux `x86` (need to disable tests). Unfortunately, it cannot be built on CI due to resource requirements needed to build the Polars Rust library.  The Azure (emulated) agents have ~7GB of RAM, and they  appears to run out of memory when building the library, local memory usage peaks at around ~11GB. Travis (native) agents appear to have a build time cut-off of 50 minutes (with `idle_timeout_minutes` of 60 minutes), and on the slow VMs that they provide, the build appears to need more than that, and as a result they timeout.

**Comment by tanaka-de-silva** [comment]
Tried quite a few permutations to no avail. The CPython packages builds fine locally when you build it natively (using Docker on Apple Silicon), and when cross-compiling for aarch64 on a Linux x86 (need to disable tests). Unfortunately, it cannot be built on CI due to resource requirements needed to build the Polars Rust library. The Azure (emulated) agents have ~7GB of RAM, and they appears to run out of memory when building the library, local memory usage peaks at around ~11GB. Travis (native) agents appear to have a build time cut-off of 50 minutes (with idle_timeout_minutes of 60 minutes), and on the slow VMs that they provide, the build appears to need more than that, and as a result they timeout. Reducing the parallelism didn't help.

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Comment by tanaka-de-silva** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
